package entities.responses;

public enum CustomResponseStatus {
    REQUEST_SUCCEEDED, INSUFFICIENT_BALANCE, UPPER_BOUND_VIOLATION, NULL_CONTENT, ILLEGAL_NEGATIVE_NUMBER, INVALID_DEPOSIT, INVALID_REQUEST
}
